name: Code Check and Vercel Deployment

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release

env:
  NODE_VERSION: 20.x

jobs:
  ci:
    name: Code Quality & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node Environment
        uses: actions/setup-node@v6
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "npm"

      - name: Install Dependencies
        run: npm ci # 'ci' command (clean install) is similar to 'install' command, except it is meant to be used in automation.

      - name: Run Unit Test Cases
        run: npm run test

      - name: Run Linting & Formatting Check (Code Quality)
        run: |
          npm run lint
          echo "Code Quality Check Complete"

  build:
    name: Built React Code
    runs-on: ubuntu-latest
    needs: [ci]
    if: github.ref == 'refs/head/release' || github.event_name == 'pull_request'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node Environment
        uses: actions/setup-node@v6
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Create Production Build
        run: npm run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: dist

  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/release'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v5
        with:
          name: frontend-build
          path: ./dist

      - name: Install Vercel CLI
        uses: npm install -g vercel # https://vercel.com/docs/cli?package-manager=npm

      - name: Deploy to Vercel Production
        run: vercel deploy --prebuilt # https://vercel.com/docs/cli/deploy
        env:
          # Use the secrets we configured in GitHub settings
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
